### PR TITLE
Add rowspan & colspan support. Fixes issue #9.

### PR DESCRIPTION
**Pull request by Mottie**

### CODE REVIEW

**Comment by danielapsmaior** [comment]
Hi, I have a complex table with multiple rowspans and the way I got it to work was putting the code like that: 

```javascript
$row.children().each(function(){
              $cell = $(this);

              // skip column if already defined
              while (tmpArray[rowIndex][cellIndex]) { cellIndex++; }

              // process rowspans
              if ($cell.filter('[rowspan]').length) {
```

That is, the while that was down in the code needs to be in the beginning.
Hope it helps someone.

**Comment by Mottie** [comment]
Hi @danielapsmaior, would you please provide an example of the complex table being used? It would be nice to add a test to make sure everything works.

**Comment by lightswitch05** [comment]
:+1: I agree with @Mottie - if you wouldn't mind providing an example for us, we can get this fixed and have a test for it

**Comment by danielapsmaior** [comment]
table-rowspan

the html for it would be (sorry it's unformatted):
<table class="pvtTable" data-numrows="36" data-numcols="0"><tr><th class="pvtAxisLabel">Rota</th><th class="pvtAxisLabel">Descrição Descritor</th><th class="pvtAxisLabel">Ano</th><th class="pvtAxisLabel">Mês (completo)</th><th class="pvtAxisLabel">Dia</th><th class="pvtAxisLabel">Intervalo 30min</th><th class="pvtTotalLabel">Totais</th></tr><tr><th class="pvtRowLabel" rowspan="14">null</th><th class="pvtRowLabel" rowspan="2">AutoAtendimento</th><th class="pvtRowLabel" rowspan="2">2015</th><th class="pvtRowLabel" rowspan="2">01-Jan</th><th class="pvtRowLabel" rowspan="2">06</th><th class="pvtRowLabel" rowspan="1">11:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row0">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="3" data-for="row1">3</td></tr><tr><th class="pvtRowLabel" rowspan="6">Fila</th><th class="pvtRowLabel" rowspan="6">2015</th><th class="pvtRowLabel" rowspan="6">01-Jan</th><th class="pvtRowLabel" rowspan="2">06</th><th class="pvtRowLabel" rowspan="1">11:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row2">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row3">2</td></tr><tr><th class="pvtRowLabel" rowspan="4">27</th><th class="pvtRowLabel" rowspan="1">11:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row4">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row5">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">15:00:00</th><td class="pvtTotal rowTotal" data-value="4" data-for="row6">4</td></tr><tr><th class="pvtRowLabel" rowspan="1">16:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row7">2</td></tr><tr><th class="pvtRowLabel" rowspan="6">Inicio</th><th class="pvtRowLabel" rowspan="6">2015</th><th class="pvtRowLabel" rowspan="6">01-Jan</th><th class="pvtRowLabel" rowspan="2">06</th><th class="pvtRowLabel" rowspan="1">11:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row8">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="5" data-for="row9">5</td></tr><tr><th class="pvtRowLabel" rowspan="4">27</th><th class="pvtRowLabel" rowspan="1">11:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row10">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row11">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">15:00:00</th><td class="pvtTotal rowTotal" data-value="4" data-for="row12">4</td></tr><tr><th class="pvtRowLabel" rowspan="1">16:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row13">2</td></tr><tr><th class="pvtRowLabel" rowspan="22">Rota externa</th><th class="pvtRowLabel" rowspan="2">AutoAtendimento</th><th class="pvtRowLabel" rowspan="2">2015</th><th class="pvtRowLabel" rowspan="2">01-Jan</th><th class="pvtRowLabel" rowspan="2">06</th><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row14">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:30:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row15">2</td></tr><tr><th class="pvtRowLabel" rowspan="9">Fila</th><th class="pvtRowLabel" rowspan="9">2015</th><th class="pvtRowLabel" rowspan="9">01-Jan</th><th class="pvtRowLabel" rowspan="2">06</th><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row16">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:30:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row17">2</td></tr><tr><th class="pvtRowLabel" rowspan="7">27</th><th class="pvtRowLabel" rowspan="1">10:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row18">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">11:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row19">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">11:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row20">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row21">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">16:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row22">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">18:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row23">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">19:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row24">1</td></tr><tr><th class="pvtRowLabel" rowspan="11">Inicio</th><th class="pvtRowLabel" rowspan="11">2015</th><th class="pvtRowLabel" rowspan="10">01-Jan</th><th class="pvtRowLabel" rowspan="2">06</th><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row25">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:30:00</th><td class="pvtTotal rowTotal" data-value="4" data-for="row26">4</td></tr><tr><th class="pvtRowLabel" rowspan="7">27</th><th class="pvtRowLabel" rowspan="1">10:30:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row27">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">11:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row28">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">11:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row29">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">12:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row30">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">16:00:00</th><td class="pvtTotal rowTotal" data-value="2" data-for="row31">2</td></tr><tr><th class="pvtRowLabel" rowspan="1">18:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row32">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">19:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row33">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">30</th><th class="pvtRowLabel" rowspan="1">20:00:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row34">1</td></tr><tr><th class="pvtRowLabel" rowspan="1">02-Feb</th><th class="pvtRowLabel" rowspan="1">03</th><th class="pvtRowLabel" rowspan="1">14:30:00</th><td class="pvtTotal rowTotal" data-value="1" data-for="row35">1</td></tr><tr><th class="pvtTotalLabel" colspan="6">Totais</th><td class="pvtGrandTotal" data-value="34">34</td></tr></table>

**Comment by lightswitch05** [comment]
@danielapsmaior thank you for the example. The code changes have been made and released in version 0.11.1. I also added the example to the testing suite, so we shouldn't have this issue again. Thank you for the info!

**Pull request merged**
