### PR TITLE
change textExtractor to extractor to support object as return value

### PR DESCRIPTION
**Pull request by koshuang**
With `extract` method, we can return a nested JSON object. e.g.

```javascript
$('table').tableToJSON({
  extractor : {
    0 : function(cellIndex, $cell) {
      return {
        name: $cell.find('em').text(),
        avatar: $cell.find('img').attr('src')
      };
    },
    1 : function(cellIndex, $cell) {
      return $cell.find('span').text();
    }
  }
});
```

### CODE REVIEW

**Comment by lightswitch05** [comment]
@koshuang thank you for your contribution, this looks promising.

However, dropping support for `textExtractor` is a breaking API change and won't work for existing users. Please add this feature along side of existing `textExtractor` and I'll be happy to merge it

**Comment by koshuang** [comment]
@lightswitch05 got it, I will update the PR soon, thanks for your response. :)

**Comment by koshuang** [comment]
@lightswitch05 I've update the the PR, could you review again? thanks!

**Comment by lightswitch05** [comment]
Thanks for your contribution!

**Comment by lightswitch05** [comment]
Included in 0.12.0

**Comment by koshuang** [comment]
thanks @lightswitch05 , would you mind pushing `0.12.0` to npm?

**Comment by lightswitch05** [comment]
@koshuang that totally slipped my mind. Its published now, sorry about the wait!

**Comment by koshuang** [comment]
@lightswitch05 great, thanks :)

**Pull request merged**
